### ISSUE TITLE
does not work with latex

### ISSUE THREAD

**Issue by nilsbecker** [cseelus/vim-colors-lucid#1]
equations in latex are almost unreadable since the bg color is changed in a weird way. 

e.g.
```
\documentclass[a4paper]{article} 
\usepackage{amsmath} 
\begin{document} 
\begin{align*} 
  S_1 > S > S_2 \\ 
  \Rightarrow S_1 & = \mathrm{e}^{}{x}  \\   
  \Rightarrow S_1 & = \mathrm{e}^{}{y} \\ 
  \Rightarrow S_1 & = \mathrm{e^{}{x} \\     
             & = \boxed{\mathrm{e}^{}{z}}    
\end{align*} 
\end{document}
```

**Comment by cseelus** [comment]
Took a while to reproduce, you probably have `conceallevel` set to `2` or something, which folds and converts LaTeX symbols on the fly.

Changed the VIM highlighting for `Concel` globally, should work for you now.

Let me know if you find other shortcomings for LaTeX, it's been a while since I used it extensively.

**Comment by nilsbecker** [comment]
thanks for looking into this. in fact my conceallevel is 0. i'm on macvim, with vim 8.0 . i'm using the lervag/vimtex package for editing latex, but i did not think that should matter (not sure)?

i updated the plugin and now the weird bg did disappear. i still see some unexpected bolding of parentheses and letters. e.g. this example:
```
\documentclass[a4paper]{article} 
\usepackage{amsmath} 
\begin{document} 

\begin{align*} 
  S_1 > S > S_2 \\ 
  \Rightarrow S_1 & = \mathrm{e}^{}{x}  \\   
  \Rightarrow S_1 & = \mathrm{e}^{}{y} \\ 
	\Rightarrow S_1 & = \mathrm{e}^{}{x} \\     
		(1,2) \left[ sdfa \right]
             & = \boxed{\mathrm{e}^{}{z}}    
		\rec_i 
	\xrightleftharpoons[k_u]{\,k_b\,} 
	\rec_i + \lig & \xrightleftharpoons[k_u]{\,k_{b,i}\,} 
\end{align*} 

the equilibrium fraction $f=C$ is 

\begin{equation}
	\label{eq:KD3d}
	K_{D,1}^\text{3d} \gg K_{D,2}^\text{3d}.
\end{equation}
Therefore, in the corresponding reaction scheme
\begin{align}
	\rec_i + \lig & \xrightleftharpoons[k_u]{\,k_{b,i}\,} 
	\rec_i\lig \quad
	\text{for} \ i \in \{1,2\}  \label{eq:ligandbinding}\\
	\rec_i + \rec_j\lig &\xrightleftharpoons[k_{d,i}]{\,k_{a,i}\,} \comp \quad 
	\text{for}\ (i,j) \in \{(1,2), (2,1)\},
	\label{eq:recruit}
\end{align}

\end{document}
```
(it won't compile some commands are not defined).

i get inconsistent bolding of `[]` after the xrightleftharpoons for instance...

**Comment by nilsbecker** [comment]
actually i just noticed, the inconsistent bolding goes away when i change the two math environments to be the same. (align* to equation in the first). is this something that the vimtex plugin does wrong? or the regular vim latex filetype?

**Comment by cseelus** [comment]
I viewed your code with VIM 8.0 without the vimtex package and only when I set `conceallevel` to `2` it collapses the math output and shows the symbols instead, but I guess we have the same output by different means then.

I matched the highlighting for the two different math environments and pushed the changes, is that what you meant?

![screen shot 2017-10-25 at 16 30 11](https://user-images.githubusercontent.com/3188392/32004337-ce550f92-b9a1-11e7-8122-ccf70bc436e0.png)

**Comment by nilsbecker** [comment]
hi, i never got any concealing in my screen output before. i had and still have conceallevel=0, and no symbol fanciness takes place. the only thing i got was a weird background color at various places inside the math environment. the subscript `_` markers but also some of the whitespace if i recall correctly. 

anyway with your earlier update that went away. what remained was inconsistent bold-symbols. in your latest output i don't see those anymore, so this seems to be working now. 

nonetheless, it seems weird to me that a colorscheme would have to know about the names of latex environments. should that not be handled within the filetype plugin?

**Comment by cseelus** [comment]
Okay, so I misunderstood that, but as the weird background color is gone for you, that should be fine i guess.

Usually the ft-plugin has sensible defaults, so little to no adaptions are necessary to make it look good with a certain colorscheme. In reality some need a little bit more care. See for example the quite popular [base16 colorscheme (Github variant)](https://github.com/chriskempson/base16-vim/blob/master/colors/base16-github.vim#L219), which has around 15 specific highlights for Git, but only four for HTML.

**Comment by nilsbecker** [comment]
yes, thanks, the weird bg color is fixed! interesting that the colorschemes have to look into the individual filetypes. i think it's perfectly understandable but definitely not ideal...

**Comment by cseelus** [comment]
Yeah certainly not ideal but also it often comes down to personal taste of the colorscheme author. 

The author may be of the opinion that a certain orange color should be the primary color of her colorscheme and when adapting say for Ruby, she thinks that Ruby symbols should be painted in that certain orange color because they are an important language feature and so she changes that, to make it feel "right" for her.

After all its some kind of styling and design, which not always has to be perfectly reasonable …

**Comment by nilsbecker** [comment]
gotcha. 'de gustibus...'
